use leptos::prelude::*;

use crate::components::icons::{Cpu, Layout, Smartphone, Zap};

// ── Version constant (generated by build.rs from workspace Cargo.toml) ───────
include!(concat!(env!("OUT_DIR"), "/version_generated.rs"));

// ── Changelog types ───────────────────────────────────────────────────────────

pub struct ChangelogChange {
    pub description: &'static str,
    pub scope: Option<&'static str>,
}

pub struct ChangelogGroup {
    pub group: &'static str,
    pub changes: Vec<ChangelogChange>,
}

pub struct ChangelogEntry {
    pub version: &'static str,
    pub date: &'static str,
    pub groups: Vec<ChangelogGroup>,
}

pub fn changelog_entries() -> Vec<ChangelogEntry> {
    include!(concat!(env!("OUT_DIR"), "/changelog_generated.rs"))
}

pub struct Feature {
    pub icon: fn() -> AnyView,
    pub title: &'static str,
    pub desc: &'static str,
}

pub fn features() -> Vec<Feature> {
    vec![
        Feature {
            icon: || view! { <Cpu class="w-6 h-6 text-blue-400" /> }.into_any(),
            title: "Blazingly Fast",
            desc: "Written in Rust for instant startup times, minimal memory usage, and zero lag even with large logs.",
        },
        Feature {
            icon: || view! { <Smartphone class="w-6 h-6 text-green-400" /> }.into_any(),
            title: "Multi-Device",
            desc: "Run up to 9 simultaneous sessions. Select multiple connected devices at once and launch them all with a single confirm.",
        },
        Feature {
            icon: || view! { <Zap class="w-6 h-6 text-yellow-400" /> }.into_any(),
            title: "Auto Hot Reload",
            desc: "Smart file watcher monitors your source files and triggers reload on save with intelligent debouncing. Watch paths are configurable (default: lib/).",
        },
        Feature {
            icon: || view! { <Layout class="w-6 h-6 text-purple-400" /> }.into_any(),
            title: "Beautiful TUI",
            desc: "Built with Ratatui. Features scrollable logs, syntax highlighting, session tabs, and vim-style navigation.",
        },
    ]
}

pub struct Keybinding {
    pub key: &'static str,
    pub action: &'static str,
    pub description: &'static str,
}

pub struct KeybindingSection {
    pub title: &'static str,
    pub color: &'static str,
    pub key_color: &'static str,
    pub bindings: Vec<Keybinding>,
}

pub fn all_keybinding_sections() -> Vec<KeybindingSection> {
    vec![
        // ── Normal Mode ──────────────────────────────────────────────
        KeybindingSection {
            title: "General Controls",
            color: "bg-blue-500",
            key_color: "text-blue-400",
            bindings: vec![
                Keybinding { key: "q", action: "Quit", description: "Request to quit (may show confirmation dialog if sessions are running)" },
                Keybinding { key: "qq", action: "Quick Quit", description: "Second q confirms the quit dialog" },
                Keybinding { key: "Esc", action: "Quit", description: "Same as q" },
                Keybinding { key: "Ctrl+C", action: "Force Quit", description: "Emergency exit, bypasses confirmation dialog" },
                Keybinding { key: "c", action: "Clear Logs", description: "Clear all logs in the current session" },
                Keybinding { key: "Alt+m", action: "Toggle Mouse Capture", description: "Suspend or resume mouse capture. Status bar shows [mouse] / [mouse-off]. Works in all modes except text-input fields." },
            ],
        },
        KeybindingSection {
            title: "Session Management",
            color: "bg-blue-500",
            key_color: "text-blue-400",
            bindings: vec![
                Keybinding { key: "1-9", action: "Switch Session", description: "Switch to session 1-9 by index" },
                Keybinding { key: "Tab", action: "Next Session", description: "Cycle to the next session" },
                Keybinding { key: "Shift+Tab", action: "Previous Session", description: "Cycle to the previous session" },
                Keybinding { key: "x", action: "Close Session", description: "Close the current session" },
                Keybinding { key: "Ctrl+W", action: "Close Session", description: "Alternative binding to close current session" },
                Keybinding { key: "+", action: "Start New Session", description: "Open New Session Dialog to configure and launch a session" },
            ],
        },
        KeybindingSection {
            title: "App Control",
            color: "bg-blue-500",
            key_color: "text-blue-400",
            bindings: vec![
                Keybinding { key: "r", action: "Hot Reload", description: "Trigger a hot reload (disabled when busy)" },
                Keybinding { key: "R", action: "Hot Restart", description: "Trigger a hot restart (disabled when busy)" },
                Keybinding { key: "s", action: "Stop App", description: "Stop the running app (disabled when busy)" },
                Keybinding { key: "D", action: "Toggle DAP Server", description: "Start or stop the DAP debug adapter server. [DAP :PORT] appears in status bar when active." },
                Keybinding { key: "V", action: "Flutter Version Panel", description: "Open the Flutter SDK version manager panel" },
                Keybinding { key: "w", action: "Toggle Wrap Mode", description: "Toggle line-wrap on/off for the log view" },
            ],
        },
        KeybindingSection {
            title: "Log Navigation",
            color: "bg-blue-500",
            key_color: "text-blue-400",
            bindings: vec![
                Keybinding { key: "j / \u{2193}", action: "Scroll Down", description: "Move down one line" },
                Keybinding { key: "k / \u{2191}", action: "Scroll Up", description: "Move up one line" },
                Keybinding { key: "g", action: "Go to Top", description: "Jump to the beginning of logs" },
                Keybinding { key: "G", action: "Go to Bottom", description: "Jump to the end of logs" },
                Keybinding { key: "Home / End", action: "Top / Bottom", description: "Alternative bindings for top/bottom" },
                Keybinding { key: "PgUp / PgDn", action: "Page Scroll", description: "Scroll up/down one page" },
                Keybinding { key: "h / \u{2190}", action: "Scroll Left", description: "Move left 10 characters" },
                Keybinding { key: "l / \u{2192}", action: "Scroll Right", description: "Move right 10 characters" },
                Keybinding { key: "0", action: "Line Start", description: "Jump to the start of the line" },
                Keybinding { key: "$", action: "Line End", description: "Jump to the end of the line" },
            ],
        },
        KeybindingSection {
            title: "Log Filtering",
            color: "bg-blue-500",
            key_color: "text-blue-400",
            bindings: vec![
                Keybinding { key: "f", action: "Cycle Level Filter", description: "Cycle through: All \u{2192} Errors \u{2192} Warnings \u{2192} Info \u{2192} Debug" },
                Keybinding { key: "F", action: "Cycle Source Filter", description: "Cycle through: All \u{2192} App \u{2192} Daemon \u{2192} Flutter \u{2192} Watcher" },
                Keybinding { key: "T / t", action: "Tag Filter Overlay", description: "Open/close native platform log tag filter overlay (both uppercase T and lowercase t work)" },
                Keybinding { key: "Ctrl+F", action: "Reset Filters", description: "Clear all active filters" },
            ],
        },
        KeybindingSection {
            title: "Log Search & Error Navigation",
            color: "bg-blue-500",
            key_color: "text-blue-400",
            bindings: vec![
                Keybinding { key: "/", action: "Start Search", description: "Enter search input mode to type a query" },
                Keybinding { key: "n", action: "Next Match", description: "Jump to the next search match" },
                Keybinding { key: "N", action: "Previous Match", description: "Jump to the previous search match" },
                Keybinding { key: "e", action: "Next Error", description: "Jump to the next error log entry" },
                Keybinding { key: "E", action: "Previous Error", description: "Jump to the previous error log entry" },
                Keybinding { key: "Enter", action: "Toggle Stack Trace", description: "Expand/collapse stack trace of the focused entry" },
                Keybinding { key: "L", action: "Enter Link Mode", description: "Highlight all file references with shortcut badges" },
            ],
        },

        // ── Loading Mode ─────────────────────────────────────────────
        KeybindingSection {
            title: "Loading Mode",
            color: "bg-gray-500",
            key_color: "text-gray-400",
            bindings: vec![
                Keybinding { key: "q", action: "Quit", description: "Quit Flutter Demon" },
                Keybinding { key: "Esc", action: "Quit", description: "Same as q" },
                Keybinding { key: "Ctrl+C", action: "Force Quit", description: "Emergency exit" },
            ],
        },

        // ── DevTools Mode ─────────────────────────────────────────────
        KeybindingSection {
            title: "DevTools \u{2014} Panel Navigation",
            color: "bg-cyan-500",
            key_color: "text-cyan-400",
            bindings: vec![
                Keybinding { key: "d", action: "Enter DevTools", description: "Enter DevTools mode (requires VM Service connection)" },
                Keybinding { key: "Esc", action: "Exit DevTools", description: "Return to Normal mode (log view)" },
                Keybinding { key: "i", action: "Inspector Panel", description: "Switch to Widget Inspector panel" },
                Keybinding { key: "p", action: "Performance Panel", description: "Switch to Performance monitoring panel" },
                Keybinding { key: "m", action: "Memory Panel", description: "Switch to Memory monitoring panel" },
                Keybinding { key: "n", action: "Network Panel", description: "Switch to Network monitoring panel" },
                Keybinding { key: "b", action: "Browser DevTools", description: "Open Flutter DevTools in system browser" },
                Keybinding { key: "q", action: "Quit", description: "Quit the application" },
            ],
        },
        KeybindingSection {
            title: "DevTools \u{2014} Debug Overlays",
            color: "bg-cyan-500",
            key_color: "text-cyan-400",
            bindings: vec![
                Keybinding { key: "Ctrl+r", action: "Repaint Rainbow", description: "Toggle repaint rainbow overlay on device" },
                Keybinding { key: "Ctrl+p", action: "Performance Overlay", description: "Toggle performance overlay on device" },
                Keybinding { key: "Ctrl+d", action: "Debug Paint", description: "Toggle debug paint overlay on device" },
            ],
        },
        KeybindingSection {
            title: "DevTools \u{2014} Widget Inspector",
            color: "bg-cyan-500",
            key_color: "text-cyan-400",
            bindings: vec![
                Keybinding { key: "\u{2191} / k", action: "Move Up", description: "Move selection up in widget tree" },
                Keybinding { key: "\u{2193} / j", action: "Move Down", description: "Move selection down in widget tree" },
                Keybinding { key: "\u{2192} / Enter", action: "Expand", description: "Expand selected tree node" },
                Keybinding { key: "\u{2190} / h", action: "Collapse", description: "Collapse selected tree node" },
                Keybinding { key: "r", action: "Refresh", description: "Refresh widget tree from VM Service" },
            ],
        },
        KeybindingSection {
            title: "DevTools \u{2014} Performance Monitor",
            color: "bg-cyan-500",
            key_color: "text-cyan-400",
            bindings: vec![
                Keybinding { key: "Tab / Shift+Tab", action: "Cycle Section Focus", description: "Cycle focus between Frame Chart and Details pane" },
                Keybinding { key: "j / \u{2193}", action: "Scroll Down", description: "Scroll focused section down" },
                Keybinding { key: "k / \u{2191}", action: "Scroll Up", description: "Scroll focused section up" },
                Keybinding { key: "PgUp / PgDn", action: "Page Scroll", description: "Page-scroll the focused section" },
                Keybinding { key: "Home / End", action: "Jump to Start / End", description: "Jump to oldest frame or live edge" },
                Keybinding { key: "\u{2190} / \u{2192}", action: "Frame Select / Gantt Pan / Sibling Nav", description: "Context-dependent: select prev/next frame, pan the Gantt chart, or navigate sibling events when an event is selected" },
                Keybinding { key: "] / [", action: "Cycle Detail Tab", description: "Cycle the Details pane tabs forward/backward (Frame Analysis \u{2192} Rebuild Stats \u{2192} Timeline Events). Only active when Details pane has focus." },
                Keybinding { key: "f", action: "Cycle Timeline Filter", description: "Cycle Timeline Events filter: All \u{2192} UI \u{2192} Raster. Only fires when Details pane focused and Timeline Events tab active." },
                Keybinding { key: "R", action: "Toggle Rebuild Tracking", description: "Toggle ext.flutter.profileWidgetBuilds. Only fires when Details pane focused and Rebuild Stats tab active. Otherwise triggers hot restart." },
                Keybinding { key: "+ / =", action: "Zoom In", description: "Zoom in on Timeline Events Gantt chart" },
                Keybinding { key: "- / _", action: "Zoom Out", description: "Zoom out on Timeline Events Gantt chart" },
                Keybinding { key: "g", action: "Follow Latest", description: "Pin Timeline Events view to the live edge (follow latest event)" },
                Keybinding { key: "/", action: "Timeline Search", description: "Open timeline event search input (on Timeline Events tab)" },
                Keybinding { key: "n / N", action: "Next / Previous Match", description: "Jump to next or previous timeline search match" },
                Keybinding { key: "Esc", action: "Deselect / Exit", description: "Deselect current frame, or exit DevTools if no frame selected" },
            ],
        },
        KeybindingSection {
            title: "DevTools \u{2014} Memory Monitor",
            color: "bg-cyan-500",
            key_color: "text-cyan-400",
            bindings: vec![
                Keybinding { key: "Tab / Shift+Tab", action: "Cycle Section Focus", description: "Cycle focus between Memory Chart and Allocation List" },
                Keybinding { key: "j / \u{2193}", action: "Scroll Down", description: "Scroll focused section down" },
                Keybinding { key: "k / \u{2191}", action: "Scroll Up", description: "Scroll focused section up" },
                Keybinding { key: "PgUp / PgDn", action: "Page Scroll", description: "Page-scroll the focused section" },
                Keybinding { key: "Home / End", action: "Jump to Start / End", description: "Jump to oldest chart sample or first/last alloc row" },
                Keybinding { key: "s", action: "Toggle Allocation Sort", description: "Toggle allocation table sort between By Size and By Instances" },
                Keybinding { key: "Esc", action: "Deselect / Exit", description: "Deselect current allocation row, or exit DevTools if nothing selected" },
            ],
        },
        KeybindingSection {
            title: "DevTools \u{2014} Network Monitor",
            color: "bg-cyan-500",
            key_color: "text-cyan-400",
            bindings: vec![
                Keybinding { key: "j / \u{2193}", action: "Navigate Down", description: "Move to next request in the list" },
                Keybinding { key: "k / \u{2191}", action: "Navigate Up", description: "Move to previous request in the list" },
                Keybinding { key: "PgDn", action: "Page Down", description: "Skip forward 10 requests" },
                Keybinding { key: "PgUp", action: "Page Up", description: "Skip back 10 requests" },
                Keybinding { key: "Enter", action: "Select Request", description: "Open request detail view for the selected request" },
                Keybinding { key: "Esc", action: "Deselect / Exit", description: "Deselect current request, or exit DevTools if nothing selected" },
                Keybinding { key: "g", action: "General Tab", description: "Switch detail view to General tab" },
                Keybinding { key: "h", action: "Headers Tab", description: "Switch detail view to Headers tab" },
                Keybinding { key: "q", action: "Request Body Tab", description: "Switch detail view to Request Body tab" },
                Keybinding { key: "s", action: "Response Body Tab", description: "Switch detail view to Response Body tab" },
                Keybinding { key: "t", action: "Timing Tab", description: "Switch detail view to Timing tab" },
                Keybinding { key: "Space", action: "Toggle Recording", description: "Start or stop recording network requests" },
                Keybinding { key: "Ctrl+X", action: "Clear History", description: "Clear all recorded network requests" },
                Keybinding { key: "/", action: "Enter Filter Mode", description: "Enter filter input mode to type a filter query" },
            ],
        },
        KeybindingSection {
            title: "Network Filter Input",
            color: "bg-cyan-500",
            key_color: "text-cyan-400",
            bindings: vec![
                Keybinding { key: "Type", action: "Filter Input", description: "Add character to filter query" },
                Keybinding { key: "Backspace", action: "Delete Character", description: "Remove last character from filter query" },
                Keybinding { key: "Enter", action: "Apply Filter", description: "Apply the filter and exit filter input mode" },
                Keybinding { key: "Esc", action: "Cancel Filter", description: "Discard filter changes and exit filter input mode" },
            ],
        },

        // ── New Session Dialog ───────────────────────────────────────
        KeybindingSection {
            title: "New Session Dialog",
            color: "bg-green-500",
            key_color: "text-green-400",
            bindings: vec![
                Keybinding { key: "Tab", action: "Switch Pane", description: "Switch focus between Target Selector and Launch Context" },
                Keybinding { key: "1 / 2", action: "Device Tabs", description: "Switch to Connected (1) or Bootable (2) devices tab" },
                Keybinding { key: "\u{2191} / k", action: "Navigate Up", description: "Move up in device list or previous field" },
                Keybinding { key: "\u{2193} / j", action: "Navigate Down", description: "Move down in device list or next field" },
                Keybinding { key: "Enter", action: "Select / Launch", description: "Select device, activate field, or launch session" },
                Keybinding { key: "\u{2190} / \u{2192}", action: "Change Mode", description: "Cycle mode (when Mode field focused)" },
                Keybinding { key: "r", action: "Refresh", description: "Refresh device list" },
                Keybinding { key: "Esc", action: "Close", description: "Close modal or dialog" },
            ],
        },

        // ── Multi-Device Launch ──────────────────────────────────────
        KeybindingSection {
            title: "Multi-Device Launch (Connected Tab)",
            color: "bg-green-500",
            key_color: "text-green-400",
            bindings: vec![
                Keybinding { key: "Space", action: "Toggle Device Selection", description: "Toggle the cursor device's checked state for multi-launch. Unsupported devices cannot be selected." },
                Keybinding { key: "a", action: "Select All / Clear All", description: "Check all supported connected devices; clears all if every supported device is already checked" },
                Keybinding { key: "Enter", action: "Launch", description: "Launch all checked devices as separate sessions; if none checked, launches only the cursor device" },
                Keybinding { key: "r", action: "Refresh Devices", description: "Refresh the connected device list" },
            ],
        },

        // ── Fuzzy Search Modal ───────────────────────────────────────
        KeybindingSection {
            title: "Fuzzy Search Modal",
            color: "bg-green-500",
            key_color: "text-green-400",
            bindings: vec![
                Keybinding { key: "Type", action: "Filter / Input", description: "Filter existing items or enter custom value" },
                Keybinding { key: "\u{2191} / \u{2193}", action: "Navigate", description: "Navigate through filtered results" },
                Keybinding { key: "Enter", action: "Confirm", description: "Select highlighted item or use custom text" },
                Keybinding { key: "Backspace", action: "Delete Char", description: "Delete last character from query" },
                Keybinding { key: "Esc", action: "Cancel", description: "Close modal without changes" },
            ],
        },

        // ── Dart Defines Modal ───────────────────────────────────────
        KeybindingSection {
            title: "Dart Defines Modal",
            color: "bg-green-500",
            key_color: "text-green-400",
            bindings: vec![
                Keybinding { key: "Tab", action: "Switch Pane", description: "Switch between List and Edit panes" },
                Keybinding { key: "\u{2191} / \u{2193}", action: "Navigate", description: "Navigate items in list pane" },
                Keybinding { key: "Enter", action: "Action", description: "Load item (List) / Save or Delete (Edit)" },
                Keybinding { key: "Esc", action: "Save & Close", description: "Save all changes and close modal" },
            ],
        },

        // ── Search Input Mode ────────────────────────────────────────
        KeybindingSection {
            title: "Search Input Mode",
            color: "bg-cyan-500",
            key_color: "text-cyan-400",
            bindings: vec![
                Keybinding { key: "Type", action: "Input Character", description: "Add character to the search query" },
                Keybinding { key: "Backspace", action: "Delete Character", description: "Remove the last character from the query" },
                Keybinding { key: "Ctrl+U", action: "Clear Input", description: "Clear the entire search query" },
                Keybinding { key: "Enter", action: "Submit Search", description: "Exit search input mode, keep query active" },
                Keybinding { key: "Esc", action: "Cancel Search", description: "Exit search input mode, keep current query" },
            ],
        },

        // ── Link Highlight Mode ──────────────────────────────────────
        KeybindingSection {
            title: "Link Highlight Mode",
            color: "bg-orange-500",
            key_color: "text-orange-400",
            bindings: vec![
                Keybinding { key: "1-9", action: "Open Link", description: "Open the file reference labeled 1-9" },
                Keybinding { key: "a-z", action: "Open Link", description: "Open the file reference labeled 10-35" },
                Keybinding { key: "j / k", action: "Scroll", description: "Scroll down/up while in link mode" },
                Keybinding { key: "PgUp / PgDn", action: "Page Scroll", description: "Scroll up/down one page" },
                Keybinding { key: "Esc / L", action: "Exit Link Mode", description: "Return to normal mode" },
            ],
        },

        // ── Settings Panel ───────────────────────────────────────────
        KeybindingSection {
            title: "Settings Panel",
            color: "bg-purple-500",
            key_color: "text-purple-400",
            bindings: vec![
                Keybinding { key: ",", action: "Open Settings", description: "Open the full-screen settings panel" },
                Keybinding { key: "Esc / q", action: "Close Settings", description: "Close settings and return to normal mode" },
                Keybinding { key: "Ctrl+S", action: "Save Settings", description: "Save changes to the current tab's configuration file" },
                Keybinding { key: "Tab", action: "Next Tab", description: "Move to the next settings tab" },
                Keybinding { key: "Shift+Tab", action: "Previous Tab", description: "Move to the previous settings tab" },
                Keybinding { key: "1-4", action: "Jump to Tab", description: "Jump to Project (1), User (2), Launch (3), or VSCode (4)" },
                Keybinding { key: "j / k", action: "Navigate", description: "Move to the next/previous setting" },
                Keybinding { key: "Enter / Space", action: "Edit / Toggle", description: "Edit the selected setting or toggle booleans/enums" },
                Keybinding { key: "+ / -", action: "Inc / Dec", description: "Increment or decrement number values" },
                Keybinding { key: "Esc", action: "Cancel Edit", description: "Cancel editing and discard changes (when editing)" },
            ],
        },

        // ── Flutter Version Mode ─────────────────────────────────────
        KeybindingSection {
            title: "Flutter Version Mode",
            color: "bg-indigo-500",
            key_color: "text-indigo-400",
            bindings: vec![
                Keybinding { key: "Esc", action: "Close Panel", description: "Close the Flutter Version panel and return to Normal mode" },
                Keybinding { key: "Tab", action: "Switch Pane", description: "Toggle focus between SDK Info and Installed Versions panes" },
                Keybinding { key: "k / \u{2191}", action: "Navigate Up", description: "Move selection up in the version list" },
                Keybinding { key: "j / \u{2193}", action: "Navigate Down", description: "Move selection down in the version list" },
                Keybinding { key: "Enter", action: "Switch Version", description: "Switch to the selected Flutter SDK version (writes .fvmrc)" },
                Keybinding { key: "d", action: "Remove Version", description: "Delete the selected SDK version from the FVM cache" },
                Keybinding { key: "i", action: "Install Version", description: "Install a Flutter version into the FVM cache" },
                Keybinding { key: "u", action: "Update Version", description: "Update the selected Flutter version" },
                Keybinding { key: "Ctrl+C", action: "Force Quit", description: "Emergency exit" },
            ],
        },

        // ── Confirm Dialog ───────────────────────────────────────────
        KeybindingSection {
            title: "Confirm Dialog",
            color: "bg-red-500",
            key_color: "text-red-400",
            bindings: vec![
                Keybinding { key: "y / Y / Enter", action: "Confirm", description: "Confirm and quit Flutter Demon" },
                Keybinding { key: "q", action: "Confirm", description: "Enables qq quick quit pattern" },
                Keybinding { key: "n / N / Esc", action: "Cancel", description: "Cancel quit and return to normal mode" },
                Keybinding { key: "Ctrl+C", action: "Force Quit", description: "Emergency exit, bypasses confirmation" },
            ],
        },

        // ── Mouse Interactions ───────────────────────────────────────
        KeybindingSection {
            title: "Mouse Interactions",
            color: "bg-pink-500",
            key_color: "text-pink-400",
            bindings: vec![
                Keybinding { key: "Wheel", action: "Scroll focused surface", description: "Routes by current UiMode; coordinate-free \u{2014} scrolls wherever focus is" },
                Keybinding { key: "Shift+Wheel", action: "Page scroll", description: "Normal / LinkHighlight / DevTools-Network only; Windows 11 drops Shift modifier" },
                Keybinding { key: "Click [r]/[R]/[x]/[d]/[D]/[q]", action: "Hot reload / restart / stop / DevTools / DAP / quit", description: "Bracketed header shortcuts; same is_busy gate as keyboard" },
                Keybinding { key: "Click session tab", action: "Switch session", description: "Left-click a tab in the tab bar" },
                Keybinding { key: "Middle-click session tab", action: "Close session", description: "Closes the clicked session without switching first" },
                Keybinding { key: "Click device pill", action: "Open New Session dialog", description: "Single-session compact header only" },
                Keybinding { key: "Click log row", action: "Register for double-click", description: "No visible action on single click" },
                Keybinding { key: "Double-click log row", action: "Toggle stack trace", description: "Within 400 ms; entry_id-matched; resets on session switch" },
                Keybinding { key: "Click DevTools sub-tab", action: "Switch panel", description: "Click [i] Inspector / [p] Performance / [m] Memory / [n] Network" },
                Keybinding { key: "Click Inspector row", action: "Select node", description: "Click expansion glyph \u{25b6}/\u{25bc} to expand or collapse" },
                Keybinding { key: "Click frame bar", action: "Select frame", description: "Performance chart; clicking outside a bar is a no-op" },
                Keybinding { key: "Click Network row", action: "Select request", description: "Details appear in side panel; click detail tab to switch view" },
                Keybinding { key: "Click NewSessionDialog tab/device/field/Launch", action: "Activate", description: "Device tabs, device list rows, launch-context fields, and Launch button are all clickable" },
                Keybinding { key: "Click ConfirmDialog Yes / No", action: "Confirm / cancel", description: "Bracket+label hit area" },
                Keybinding { key: "Click TagFilter row", action: "Toggle tag visibility", description: "Single click selects and toggles the tag" },
                Keybinding { key: "Click LinkHighlight badge", action: "Open link", description: "Three-cell hit area per badge" },
                Keybinding { key: "Click Settings row", action: "Select row", description: "Double-click within 400 ms enters edit mode" },
            ],
        },
    ]
}
