//! # Test Helper Backends
//!
//! This module provides shared test infrastructure for `fdemon-dap` adapter
//! tests. It defines the [`MockTestBackend`] trait with default no-op
//! implementations for all [`DebugBackend`] methods, plus a blanket
//! [`DebugBackend`] implementation for any type that implements
//! [`MockTestBackend`].
//!
//! ## Usage
//!
//! Implement only the methods your test needs; everything else falls back to
//! the safe no-op default:
//!
//! ```ignore
//! use super::test_helpers::MockTestBackend;
//!
//! struct MyMock;
//!
//! impl MockTestBackend for MyMock {
//!     // Override only what the test needs.
//!     // Use `async fn` for methods that capture `&self` fields:
//!     async fn get_vm(&self) -> Result<serde_json::Value, super::BackendError> {
//!         Ok(serde_json::json!({ "isolates": [] }))
//!     }
//! }
//! ```
//!
//! ## Adding a new `DebugBackend` method
//!
//! When a new method is added to [`DebugBackend`]:
//! 1. Add a default implementation to [`MockTestBackend`] here (one place).
//! 2. Update the blanket [`DebugBackend`] impl delegation below (one place).
//! 3. Individual mocks that need custom behaviour can then override the new
//!    method in their own `impl MockTestBackend for Foo { … }`.
//!
//! ## Why `async fn` overrides work
//!
//! The blanket `DebugBackend` impl delegates through `MockTestBackend` methods
//! via `.await`. `DebugBackend` (generated by `trait_variant::make`) requires
//! `Send` futures. Default implementations use `std::future::ready(...)` which
//! is always `Send`. Override `async fn` bodies produce `Send` futures as long
//! as all captured `&self` fields implement `Send` (which is required by the
//! `MockTestBackend: Send + Sync + 'static` bound).

use std::future::{self, Future};

use super::{BackendError, BreakpointResult, DapExceptionPauseMode, DebugBackend, StepMode};

// ─────────────────────────────────────────────────────────────────────────────
// MockTestBackend — trait with safe no-op defaults
// ─────────────────────────────────────────────────────────────────────────────

/// Test-only trait providing default no-op implementations for every
/// [`DebugBackend`] method.
///
/// Implement this for a test struct, overriding only the methods that matter
/// for the specific test scenario. The blanket [`DebugBackend`] impl below
/// wires up the delegation automatically.
///
/// **Update here first** when a new [`DebugBackend`] method is added so that
/// all existing mocks automatically inherit a safe default.
///
/// Default implementations use `std::future::ready(...)` to return immediately-
/// resolved `Send` futures, satisfying the `DebugBackend: Send` bound generated
/// by `trait_variant::make`. Override methods use `async fn`, which produces
/// `Send` futures when all captured `&self` fields are `Send`.
pub(crate) trait MockTestBackend: Send + Sync + 'static {
    // ── Execution control ─────────────────────────────────────────────────

    fn pause(&self, _isolate_id: &str) -> impl Future<Output = Result<(), BackendError>> + Send {
        future::ready(Ok(()))
    }

    fn resume(
        &self,
        _isolate_id: &str,
        _step: Option<StepMode>,
    ) -> impl Future<Output = Result<(), BackendError>> + Send {
        future::ready(Ok(()))
    }

    // ── Breakpoints ───────────────────────────────────────────────────────

    /// Default: echoes the requested line as the VM breakpoint ID so tests can
    /// distinguish breakpoints set on different lines.
    fn add_breakpoint(
        &self,
        _isolate_id: &str,
        _uri: &str,
        line: i32,
        column: Option<i32>,
    ) -> impl Future<Output = Result<BreakpointResult, BackendError>> + Send {
        future::ready(Ok(BreakpointResult {
            vm_id: format!("bp/line:{line}"),
            resolved: true,
            line: Some(line),
            column,
        }))
    }

    fn remove_breakpoint(
        &self,
        _isolate_id: &str,
        _breakpoint_id: &str,
    ) -> impl Future<Output = Result<(), BackendError>> + Send {
        future::ready(Ok(()))
    }

    fn set_exception_pause_mode(
        &self,
        _isolate_id: &str,
        _mode: DapExceptionPauseMode,
    ) -> impl Future<Output = Result<(), BackendError>> + Send {
        future::ready(Ok(()))
    }

    // ── Stack inspection ──────────────────────────────────────────────────

    fn get_stack(
        &self,
        _isolate_id: &str,
        _limit: Option<i32>,
    ) -> impl Future<Output = Result<serde_json::Value, BackendError>> + Send {
        future::ready(Ok(serde_json::json!({})))
    }

    fn get_object(
        &self,
        _isolate_id: &str,
        _object_id: &str,
        _offset: Option<i64>,
        _count: Option<i64>,
    ) -> impl Future<Output = Result<serde_json::Value, BackendError>> + Send {
        future::ready(Ok(serde_json::json!({})))
    }

    // ── Evaluation ────────────────────────────────────────────────────────

    fn evaluate(
        &self,
        _isolate_id: &str,
        _target_id: &str,
        _expression: &str,
    ) -> impl Future<Output = Result<serde_json::Value, BackendError>> + Send {
        future::ready(Ok(serde_json::json!({})))
    }

    fn evaluate_in_frame(
        &self,
        _isolate_id: &str,
        _frame_index: i32,
        _expression: &str,
    ) -> impl Future<Output = Result<serde_json::Value, BackendError>> + Send {
        future::ready(Ok(serde_json::json!({})))
    }

    // ── Thread / isolate info ─────────────────────────────────────────────

    fn get_vm(&self) -> impl Future<Output = Result<serde_json::Value, BackendError>> + Send {
        future::ready(Ok(serde_json::json!({})))
    }

    fn get_scripts(
        &self,
        _isolate_id: &str,
    ) -> impl Future<Output = Result<serde_json::Value, BackendError>> + Send {
        future::ready(Ok(serde_json::json!({})))
    }

    // ── Source retrieval ──────────────────────────────────────────────────

    fn get_source(
        &self,
        _isolate_id: &str,
        _script_id: &str,
    ) -> impl Future<Output = Result<String, String>> + Send {
        future::ready(Ok(String::new()))
    }

    // ── Hot reload / restart ──────────────────────────────────────────────

    fn hot_reload(&self) -> impl Future<Output = Result<(), BackendError>> + Send {
        future::ready(Ok(()))
    }

    fn hot_restart(&self) -> impl Future<Output = Result<(), BackendError>> + Send {
        future::ready(Ok(()))
    }

    fn stop_app(&self) -> impl Future<Output = Result<(), BackendError>> + Send {
        future::ready(Ok(()))
    }

    // ── Session metadata ──────────────────────────────────────────────────

    fn ws_uri(&self) -> impl Future<Output = Option<String>> + Send {
        future::ready(None)
    }

    fn device_id(&self) -> impl Future<Output = Option<String>> + Send {
        future::ready(None)
    }

    fn build_mode(&self) -> impl Future<Output = String> + Send {
        future::ready("debug".to_string())
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Blanket DebugBackend impl for MockTestBackend
// ─────────────────────────────────────────────────────────────────────────────

/// Blanket implementation: any [`MockTestBackend`] automatically satisfies
/// the [`DebugBackend`] bound used by [`super::DapAdapter`].
///
/// **Update here** (alongside [`MockTestBackend`]) when a new method is added
/// to [`DebugBackend`].
impl<T: MockTestBackend> DebugBackend for T {
    async fn pause(&self, isolate_id: &str) -> Result<(), BackendError> {
        MockTestBackend::pause(self, isolate_id).await
    }

    async fn resume(&self, isolate_id: &str, step: Option<StepMode>) -> Result<(), BackendError> {
        MockTestBackend::resume(self, isolate_id, step).await
    }

    async fn add_breakpoint(
        &self,
        isolate_id: &str,
        uri: &str,
        line: i32,
        column: Option<i32>,
    ) -> Result<BreakpointResult, BackendError> {
        MockTestBackend::add_breakpoint(self, isolate_id, uri, line, column).await
    }

    async fn remove_breakpoint(
        &self,
        isolate_id: &str,
        breakpoint_id: &str,
    ) -> Result<(), BackendError> {
        MockTestBackend::remove_breakpoint(self, isolate_id, breakpoint_id).await
    }

    async fn set_exception_pause_mode(
        &self,
        isolate_id: &str,
        mode: DapExceptionPauseMode,
    ) -> Result<(), BackendError> {
        MockTestBackend::set_exception_pause_mode(self, isolate_id, mode).await
    }

    async fn get_stack(
        &self,
        isolate_id: &str,
        limit: Option<i32>,
    ) -> Result<serde_json::Value, BackendError> {
        MockTestBackend::get_stack(self, isolate_id, limit).await
    }

    async fn get_object(
        &self,
        isolate_id: &str,
        object_id: &str,
        offset: Option<i64>,
        count: Option<i64>,
    ) -> Result<serde_json::Value, BackendError> {
        MockTestBackend::get_object(self, isolate_id, object_id, offset, count).await
    }

    async fn evaluate(
        &self,
        isolate_id: &str,
        target_id: &str,
        expression: &str,
    ) -> Result<serde_json::Value, BackendError> {
        MockTestBackend::evaluate(self, isolate_id, target_id, expression).await
    }

    async fn evaluate_in_frame(
        &self,
        isolate_id: &str,
        frame_index: i32,
        expression: &str,
    ) -> Result<serde_json::Value, BackendError> {
        MockTestBackend::evaluate_in_frame(self, isolate_id, frame_index, expression).await
    }

    async fn get_vm(&self) -> Result<serde_json::Value, BackendError> {
        MockTestBackend::get_vm(self).await
    }

    async fn get_scripts(&self, isolate_id: &str) -> Result<serde_json::Value, BackendError> {
        MockTestBackend::get_scripts(self, isolate_id).await
    }

    async fn get_source(&self, isolate_id: &str, script_id: &str) -> Result<String, String> {
        MockTestBackend::get_source(self, isolate_id, script_id).await
    }

    async fn hot_reload(&self) -> Result<(), BackendError> {
        MockTestBackend::hot_reload(self).await
    }

    async fn hot_restart(&self) -> Result<(), BackendError> {
        MockTestBackend::hot_restart(self).await
    }

    async fn stop_app(&self) -> Result<(), BackendError> {
        MockTestBackend::stop_app(self).await
    }

    async fn ws_uri(&self) -> Option<String> {
        MockTestBackend::ws_uri(self).await
    }

    async fn device_id(&self) -> Option<String> {
        MockTestBackend::device_id(self).await
    }

    async fn build_mode(&self) -> String {
        MockTestBackend::build_mode(self).await
    }
}
